# Generated by Django 5.0.4 on 2024-05-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FHE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('abnormality', models.CharField(max_length=100)),
                ('numbers', models.JSONField()),
            ],
        ),
    ]
