# Generated by Django 5.0.4 on 2024-05-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FHE', '0002_weekdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=100)),
                ('doctorname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('relevantinfo', models.CharField(max_length=300)),
                ('uuid', models.CharField(max_length=100)),
            ],
        ),
    ]
